[server]
address = "0.0.0.0"
port = 8501
enableCORS = true
enableXsrfProtection = false

[browser]
serverAddress = "192.168.0.110"
gatherUsageStats = false

[theme]
primaryColor = "#4287f5"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1f2c"
textColor = "#fafafa"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = true
